### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by hansmbakker** [rainforest-alliance-ms-poc/.github#1]
```[tasklist]
### Tasks
- [ ] Enable API authentication
- [ ] Enable infrastructure scanning via checkov
- [ ] Enable container scanning
- [ ] Enable github advanced security
```
